<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "<head>\n";
print "    <meta charset=\"UTF-8\">\n";
print "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
print "    <title>Dominique&co</title>\n";
print "    <link rel=\"stylesheet\" href=\"style.css\">\n";
print "    <link\n";
print "    href=\"https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css\"\n";
print "    rel=\"stylesheet\"/>\n";
print "    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css\"/>\n";
print "   \n";
print "</head>\n";
print "<body>\n";
print "    <div id=\"page\" class=\"site\">\n";
print "        <header>\n";
print "          <div class=\"header-top\">\n";
print "            <div class=\"container\">\n";
print "                <div class=\"wrap\">\n";
print "                    <div class=\"socials\">\n";
print "                        <ul>\n";
print "                            <li><a href=\"#\"><i class=\"ri-facebook-circle-line\"></i><span>300k Followers</span></a></li>\n";
print "                            <li><a href=\"#\"><i class=\"ri-instagram-line\"></i><span>5M Followers</span></a></li>\n";
print "                        </ul>\n";
print "                    </div>\n";
print "                    <div class=\"options\">\n";
print "                        <div class=\"langs\">\n";
print "                            <ul>\n";
print "                                <li><a href=\"\"><span class=\"flag us\"></span><span>Francais</span><i class=\"ri-arrow-down-s-line\"></i></a>\n";
print "                                    <ul>\n";
print "                                        <li><a href=\"#\"><span class=\"flag de\"></span><spa>Anglais</spa></a></li>\n";
print "                                        <li><a href=\"#\"><span class=\"flag id\"></span><spa>Chinois</spa></a></li>\n";
print "                                    </ul>\n";
print "                                </li>\n";
print "                            </ul>\n";
print "                        </div>\n";
print "                        <div class=\"currency\">\n";
print "                            <ul>\n";
print "                                <li><a href=\"\"><span>Euro</span><i class=\"ri-arrow-down-s-line\"></i></a>\n";
print "                                    <ul>\n";
print "                                        <li><a href=\"#\"><span>USD</span></a></li>\n";
print "                                        <li><a href=\"#\"><span>Yuan</span></a></li>\n";
print "                                    </ul>\n";
print "                                </li>\n";
print "                            </ul>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "          </div>\n";
print "          <div class=\"header-main\">\n";
print "            <div class=\"container\">\n";
print "                <div class=\"wrap\">\n";
print "                    <nav>\n";
print "                        <a href=\"#\" class=\"menu-trigger\" data-open-btn><i class=\"ri-menu-line\"></i></a>\n";
print "                        <ul>\n";
print "                            <li><a href=\"#\"><span>Acceuil</span></a></li>\n";
print "                            <li><a href=\"#\"><span>Produits</span><i class=\"ri-arrow-down-s-line\"></i></a>\n";
print "                                <div class=\"megamenu\">\n";
print "                                    <div class=\"container\">\n";
print "                                        <wrap>\n";
print "                                            <div class=\"menus\">\n";
print "                                                <div class=\"links\">\n";
print "                                                    <h3>Sweatshirt</h3>\n";
print "                                                    <ul>\n";
print "                                                        <li><a href=\"#\">Prada</a></li>\n";
print "                                                        <li><a href=\"#\">Gucci</a></li>\n";
print "                                                        <li><a href=\"#\">Chanel</a></li>\n";
print "                                                        <li><a href=\"#\">Ganni</a></li>\n";
print "                                                        <li><a href=\"#\">Zara</a></li>\n";
print "                                                        <li><a href=\"#\">Mango</a></li>\n";
print "                                                        <li><a href=\"#\">H&M</a></li>\n";
print "                                                    </ul>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                            <div class=\"featured\">\n";
print "                                                <h3>Produits populaires</h3>\n";
print "                                                <div class=\"product object-cover\">\n";
print "                                                    <div class=\"list\">\n";
print "                                                        <div class=\"product-thumb\">\n";
print "                                                            <span class=\"label\">25% OFF</span>\n";
print "                                                            <div class=\"thumbnail\">\n";
print "                                                                <a href=\"#\">\n";
print "                                                                    <div class=\"image\">\n";
print "                                                                        <img src=\"/assets/Louis vuiton sweatshirt 1.avif\">\n";
print "                                                                    </div>\n";
print "                                                                    <div class=\"image hover-image\">\n";
print "                                                                        <img src=\"/assets/Louis vuiton sweatshirt 2.avif\">\n";
print "                                                                    </div>\n";
print "                                                                </a>\n";
print "                                                            </div>\n";
print "                                                            <div class=\"icons-act\">\n";
print "                                                                <ul>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                                </ul>\n";
print "                                                            </div>\n";
print "                                                        </div>\n";
print "                                                         <div class=\"product-info\">\n";
print "                                                            <div class=\"price\">\n";
print "                                                            <h2><a href=\"#\">Louis Vuitton Sweatshirt</a></h2>\n";
print "                                                            <span class=\"before\">$1250.00</span>\n";
print "                                                            <span class=\"current\">$1000.00</span>   \n";
print "                                                            </div>\n";
print "                                                        </div>\n";
print "                                                    </div>\n";
print "                                                    <div class=\"list\">\n";
print "                                                        <div class=\"product-thumb\">\n";
print "                                                            <span class=\"label\">20% OFF</span>\n";
print "                                                            <div class=\"thumbnail\">\n";
print "                                                                <a href=\"#\">\n";
print "                                                                    <div class=\"image\">\n";
print "                                                                        <img src=\"/assets/Lacoste 1.avif\">\n";
print "                                                                    </div>\n";
print "                                                                    <div class=\"image hover-image\">\n";
print "                                                                        <img src=\"/assets/Lacoste 2.avif\">\n";
print "                                                                    </div>\n";
print "                                                                </a>\n";
print "                                                            </div>\n";
print "                                                            <div class=\"icons-act\">\n";
print "                                                                <ul>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                                </ul>\n";
print "                                                            </div>\n";
print "                                                        </div>\n";
print "                                                         <div class=\"product-info\">\n";
print "                                                            <div class=\"price\">\n";
print "                                                            <h2><a href=\"#\">Lacoste Sweatshirt</a></h2>\n";
print "                                                            <span class=\"before\">$140.00</span>\n";
print "                                                            <span class=\"current\">$112.00</span>   \n";
print "                                                            </div>\n";
print "                                                        </div>\n";
print "                                                    </div>\n";
print "                                                    <div class=\"list\">\n";
print "                                                        <div class=\"product-thumb\">\n";
print "                                                            <div class=\"thumbnail\">\n";
print "                                                                <a href=\"#\">\n";
print "                                                                    <div class=\"image\">\n";
print "                                                                        <img src=\"/assets/Prada Sweatshirt 1.avif\">\n";
print "                                                                    </div>\n";
print "                                                                    <div class=\"image hover-image\">\n";
print "                                                                        <img src=\"/assets/prada Sweatshirt 2.avif\">\n";
print "                                                                    </div>\n";
print "                                                                </a>\n";
print "                                                            </div>\n";
print "                                                            <div class=\"icons-act\">\n";
print "                                                                <ul>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                                    <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                                </ul>\n";
print "                                                            </div>\n";
print "                                                        </div>\n";
print "                                                         <div class=\"product-info\">\n";
print "                                                            <div class=\"price\">\n";
print "                                                            <h2><a href=\"#\">Prada sweatshirt</a></h2>\n";
print "                                                            <span class=\"current\">$1299.00</span>   \n";
print "                                                            </div>\n";
print "                                                        </div>\n";
print "                                                    </div>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                        </wrap>\n";
print "                                    </div>\n";
print "                                </div>\n";
print "                            </li>\n";
print "                            <li><a href=\"#\"><span>Boutique</span></a></li>\n";
print "                            <li><a href=\"#\"><span>Blog</span><i class=\"ri-arrow-down-s-line\"></i></a>\n";
print "\n";
print "                                <ul class=\"submenu\">\n";
print "                                    <li><a href=\"#\">Latest</a></li>\n";
print "                                    <li><a href=\"#\">Jumper</a></li>\n";
print "                                    <li><a href=\"#\">A Must Read</a></li>\n";
print "                                    <li><a href=\"#\">Goes viral</a></li>\n";
print "                                </ul>\n";
print "                            \n";
print "                            </li>\n";
print "                        </ul>\n";
print "                    </nav>\n";
print "                    <div class=\"logo\"><a href=\"#\">Dominique&co</a></div>\n";
print "                    <div class=\"icons\">\n";
print "                        <ul>\n";
print "                            <li><a href=\"\" data-open-btn><i class=\"ri-search-line\"></i></a></li>\n";
print "                            <li><a href=\"\"><i class=\"ri-heart-line\"></i><span class=\"qty\">5</span></a></li>\n";
print "                            <li><a href=\"\"><i class=\"ri-user-line\"></i></a></li>\n";
print "                            <li><a href=\"\"><i class=\"ri-shopping-bag-2-line\"></i><span class=\"qty\">2</span></a></li>\n";
print "                        </ul>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "          </div>\n";
print "        </header>\n";
print "        <main>\n";
print "            <div class=\"hero\">\n";
print "                <div class=\"container\">\n";
print "                    <div class=\"wrap object-cover\">\n";
print "                            <div class=\"list big\">\n";
print "                                <a href=\"#\">\n";
print "                                    <div class=\"image\">\n";
print "                                        <img src=\"assets/mannequin capuche 2.webp\">\n";
print "                                    </div>\n";
print "                                    <div class=\"info\">\n";
print "                                        <div class=\"btn-light\">Achetez Maintenant</div>\n";
print "                                    </div>\n";
print "                                </a>\n";
print "                            </div>\n";
print "                            <div class=\"list\">\n";
print "                                <a href=\"#\">\n";
print "                                    <div class=\"image\">\n";
print "                                        <img src=\"assets/Louis vuitton mannequin sweatshirt.avif\">\n";
print "                                    </div>\n";
print "                                    <div class=\"info\">\n";
print "                                        <div class=\"btn-light\">Sweatshirt</div>\n";
print "                                    </div>\n";
print "                                </a>\n";
print "                            </div>\n";
print "                            <div class=\"list\">\n";
print "                                <a href=\"#\">\n";
print "                                    <div class=\"image\">\n";
print "                                        <img src=\"assets/12334556.avif\">\n";
print "                                    </div>\n";
print "                                    <div class=\"info\">\n";
print "                                        <div class=\"btn-light\">Achetez Maintenant</div>\n";
print "                                    </div>\n";
print "                                </a>\n";
print "                            </div>\n";
print "                            <div class=\"list\">\n";
print "                                <a href=\"#\">\n";
print "                                    <div class=\"image\">\n";
print "                                        <img src=\"assets/louis-vuitton-sweatshirt-monogram-à-capuche-et-fermeture-à-glissière-prêt-à-porter--HPY33WZA8MU1_PM1_Cropped view.avif\">\n";
print "                                    </div>\n";
print "                                    <div class=\"info\">\n";
print "                                        <div class=\"btn-light\">Achetez Maintenant</div>\n";
print "                                    </div>\n";
print "                                </a>\n";
print "                            </div>\n";
print "                            <div class=\"list\">\n";
print "                                <a href=\"#\">\n";
print "                                    <div class=\"image\">\n";
print "                                        <img src=\"assets/louis-vuitton-sweat-à-capuche-zippé-et-brodé-en-jersey-prêt-à-porter--HRY42WCFJ70C_PM1_Cropped view.avif\">\n";
print "                                    </div>\n";
print "                                    <div class=\"info\">\n";
print "                                        <div class=\"btn-light\">Achetez Maintenant</div>\n";
print "                                    </div>\n";
print "                                </a>\n";
print "                            </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "\n";
print "            <div class=\"tabbed\">\n";
print "                <div class=\"container\">\n";
print "                    <div class=\"wrap\">\n";
print "                        <nav class=\"tabs\">\n";
print "                            <ul class=\"swiper-wrapper\">\n";
print "                                <li class=\"swiper-slide active\"><a href=\"#0\">New Arrivals</a></li>\n";
print "                                <li class=\"swiper-slide\"><a href=\"#0\">On sale</a></li>\n";
print "                                <li class=\"swiper-slide\"><a href=\"#0\">Best Seller</a></li>\n";
print "                            </ul>\n";
print "                        </nav>\n";
print "                        <div class=\"tabs-box swiper\">\n";
print "                            <div class=\"swiper-wrapper\">\n";
print "                                <div class=\"swiper-slide\">\n";
print "                                    <div class=\"product object-cover\">\n";
print "                                        <div class=\"list\">\n";
print "                                            <div class=\"product-thumb\">\n";
print "                                                <span class=\"label\">25% OFF</span>\n";
print "                                                <div class=\"thumbnail\">\n";
print "                                                    <a href=\"#\">\n";
print "                                                        <div class=\"image\">\n";
print "                                                            <img src=\"/assets/Louis vuiton sweatshirt 1.avif\">\n";
print "                                                        </div>\n";
print "                                                        <div class=\"image hover-image\">\n";
print "                                                            <img src=\"/assets/Louis vuiton sweatshirt 2.avif\">\n";
print "                                                        </div>\n";
print "                                                    </a>\n";
print "                                                </div>\n";
print "                                                <div class=\"icons-act\">\n";
print "                                                    <ul>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                    </ul>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                             <div class=\"product-info\">\n";
print "                                                <div class=\"colors\">\n";
print "                                                    <a href=\"#\" class=\"maroon active\"></a>\n";
print "                                                    <a href=\"#\" class=\"gold\"></a>\n";
print "                                                </div>\n";
print "                                                <div class=\"price\">\n";
print "                                                <h2><a href=\"#\">Louis Vuitton Sweatshirt</a></h2>\n";
print "                                                <span class=\"before\">$1250.00</span>\n";
print "                                                <span class=\"current\">$1000.00</span>   \n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                        </div>\n";
print "                                        <div class=\"list\">\n";
print "                                            <div class=\"product-thumb\">\n";
print "                                                <div class=\"thumbnail\">\n";
print "                                                    <a href=\"#\">\n";
print "                                                        <div class=\"image\">\n";
print "                                                            <img src=\"/assets/AMI PARIS 1.webp\">\n";
print "                                                        </div>\n";
print "                                                        <div class=\"image hover-image\">\n";
print "                                                            <img src=\"/assets/AMI PARIS 2.webp\">\n";
print "                                                        </div>\n";
print "                                                    </a>\n";
print "                                                </div>\n";
print "                                                <div class=\"icons-act\">\n";
print "                                                    <ul>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                    </ul>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                             <div class=\"product-info\">\n";
print "                                                <div class=\"colors\">\n";
print "                                                    <a href=\"#\" class=\"maroon active\"></a>\n";
print "                                                    <a href=\"#\" class=\"gold\"></a>\n";
print "                                                </div>\n";
print "                                                <div class=\"price\">\n";
print "                                                <h2><a href=\"#\">AMI PARIS</a></h2>\n";
print "                                                <span class=\"current\">$380</span>   \n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                        </div>\n";
print "                                        <div class=\"list\">\n";
print "                                            <div class=\"product-thumb\">\n";
print "                                                <div class=\"thumbnail\">\n";
print "                                                    <a href=\"#\">\n";
print "                                                        <div class=\"image\">\n";
print "                                                            <img src=\"/assets/Belluti 1.jpg\">\n";
print "                                                        </div>\n";
print "                                                        <div class=\"image hover-image\">\n";
print "                                                            <img src=\"/assets/Belluti 2.jpg\">\n";
print "                                                        </div>\n";
print "                                                    </a>\n";
print "                                                </div>\n";
print "                                                <div class=\"icons-act\">\n";
print "                                                    <ul>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                    </ul>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                             <div class=\"product-info\">\n";
print "                                                <div class=\"colors\">\n";
print "                                                    <a href=\"#\" class=\"maroon active\"></a>\n";
print "                                                    <a href=\"#\" class=\"gold\"></a>\n";
print "                                                </div>\n";
print "                                                <div class=\"price\">\n";
print "                                                <h2><a href=\"#\">Pull Avec Jacquard Scritto Marbeuf</a></h2>\n";
print "                                                <span class=\"current\">$1,300</span>   \n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                        </div>\n";
print "                                        <div class=\"list\">\n";
print "                                            <div class=\"product-thumb\">\n";
print "                                                <div class=\"thumbnail\">\n";
print "                                                    <a href=\"#\">\n";
print "                                                        <div class=\"image\">\n";
print "                                                            <img src=\"/assets/Gucci 1.avif\">\n";
print "                                                        </div>\n";
print "                                                        <div class=\"image hover-image\">\n";
print "                                                            <img src=\"/assets/Gucci 2.avif\">\n";
print "                                                        </div>\n";
print "                                                    </a>\n";
print "                                                </div>\n";
print "                                                <div class=\"icons-act\">\n";
print "                                                    <ul>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                    </ul>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                             <div class=\"product-info\">\n";
print "                                                <div class=\"colors\">\n";
print "                                                    <a href=\"#\" class=\"maroon active\"></a>\n";
print "                                                    <a href=\"#\" class=\"gold\"></a>\n";
print "                                                </div>\n";
print "                                                <div class=\"price\">\n";
print "                                                <h2><a href=\"#\">SWEAT-SHIRT EN MAILLE DE COTON GG</a></h2>\n";
print "                                                <span class=\"current\">$880</span>   \n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                        </div>\n";
print "                                        <div class=\"list\">\n";
print "                                            <div class=\"product-thumb\">\n";
print "                                                <div class=\"thumbnail\">\n";
print "                                                    <a href=\"#\">\n";
print "                                                        <div class=\"image\">\n";
print "                                                            <img src=\"/assets/Louis vuitton 1 polaire.avif\">\n";
print "                                                        </div>\n";
print "                                                        <div class=\"image hover-image\">\n";
print "                                                            <img src=\"/assets/Louis vuitton 3.avif\">\n";
print "                                                        </div>\n";
print "                                                    </a>\n";
print "                                                </div>\n";
print "                                                <div class=\"icons-act\">\n";
print "                                                    <ul>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-heart-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-shuffle-line\"></i></a></li>\n";
print "                                                        <li><a href=\"#\"><i class=\"ri-eye-line\"></i></a></li>\n";
print "                                                    </ul>\n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                             <div class=\"product-info\">\n";
print "                                                <div class=\"colors\">\n";
print "                                                    <a href=\"#\" class=\"maroon active\"></a>\n";
print "                                                    <a href=\"#\" class=\"gold\"></a>\n";
print "                                                </div>\n";
print "                                                <div class=\"price\">\n";
print "                                                <h2><a href=\"#\">Parka en polaire Monogram</a></h2>\n";
print "                                                <span class=\"current\">$2900</span>   \n";
print "                                                </div>\n";
print "                                            </div>\n";
print "                                        </div>\n";
print "                                        \n";
print "                                    </div>\n";
print "                                    <div class=\"button\">\n";
print "                                        <a href=\"#\" class=\"btn-primary\">Load More</a>\n";
print "                                    </div>\n";
print "                                </div>\n";
print "                                <div class=\"swiper-slide\">\n";
print "                                    <p>test</p>\n";
print "                                </div>\n";
print "                                <div class=\"swiper-slide\">\n";
print "                                    <p>ooo</p>\n";
print "                                </div>\n";
print "                            </div>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "\n";
print "            <div class=\"video\">\n";
print "                <div class=\"container\">\n";
print "                    <div class=\"wrap\">\n";
print "                        <div class=\"video-box object-cover\" data-open-btn>\n";
print "                            <div class=\"image\">\n";
print "                                <img src=\"assets/hero_06.jpg\">\n";
print "                            </div>\n";
print "                            <div class=\"attributes\">\n";
print "                                <i class=\"ri-play-fill\"></i>\n";
print "                                <h3>L'ambassadeur</h3>\n";
print "                            </div>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "\n";
print "\n";
print "            <div class=\"banner\">\n";
print "                <div class=\"container\">\n";
print "                    <div class=\"wrap object-cover\">\n";
print "                        <div class=\"bg-image\">\n";
print "                            <img src=\"assets/hero_07.png\" alt=\"\">\n";
print "                        </div>\n";
print "                        <div class=\"info\">\n";
print "                            <span>Hot Deals</span>\n";
print "                            <h3>Casual Dress</h3>\n";
print "                            <div class=\"button\">\n";
print "                                <a href=\"#\" class=\"btn-light\">Achetez maitenant</a>\n";
print "                            </div>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "        </main>\n";
print "        <footer>\n";
print "            <div class=\"inner-footer\">\n";
print "                <div class=\"container\">\n";
print "                    <div class=\"wrap\">\n";
print "                        <div class=\"socials\">\n";
print "                            <h3>Réseaux Sociaux</h3>\n";
print "                            <ul>\n";
print "                                <li><a href=\"#\"><i class=\"ri-facebbok-line\"></i></a></li>\n";
print "                                <li><a href=\"#\"><i class=\"ri-instagram-line\"></i></a></li>\n";
print "                                <li><a href=\"#\"><i class=\"ri-twitter-line\"></i></a></li>\n";
print "                                <li><a href=\"#\"><i class=\"ri-pinterest-line\"></i></a></li>\n";
print "                            </ul>\n";
print "                        </div>\n";
print "                        <div class=\"links\">\n";
print "                            <h3>Service</h3>\n";
print "                            <ul>\n";
print "                                <li><a href=\"#\">ABout Us</a></li>\n";
print "                                <li><a href=\"#\">Careers</a></li>\n";
print "                                <li><a href=\"#\">Delivery Information</a></li>\n";
print "                                <li><a href=\"#\">Terms & Condition</a></li>\n";
print "                                <li><a href=\"#\">Privacy Policy</a></li>\n";
print "                            </ul>\n";
print "                        </div>\n";
print "                        <div class=\"links\">\n";
print "                            <h3>Company</h3>\n";
print "                            <div class=\"comp-address\">\n";
print "                                <p>Simpang 5 No.1<br>Central Java - ID</p>\n";
print "                                <p>\n";
print "                                    <a href=\"#\">+62123456789</a>\n";
print "                                    <br>\n";
print "                                    <a href=\"#\">Dominique&co@youtube.com</a>\n";
print "                                </p>\n";
print "                                <p>\n";
print "                                    weekdays: 6AM to 6PM <br>\n";
print "                                    Saturday: 6AM to 3PM <br>\n";
print "                                    Sunday: Closed \n";
print "                                </p>\n";
print "                            </div>\n";
print "                        </div>\n";
print "                        <div class=\"subscribe\">\n";
print "                            <h3>Get Voucher from us</h3>\n";
print "                            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo facilis, porro explicabo mollitia voluptatem natus incidunt quibusdam aspernatur saepe assumenda et nisi atque</p>\n";
print "                            <form action=\"\" class=\"search\">\n";
print "                                <i class=\"ri-mail-line\"></i>\n";
print "                                <input type=\"text\" placeholder=\"Enter Your email\">\n";
print "                                <input type=\"submit\">\n";
print "                                <i class=\"ri-arrow-right-line\"></i>\n";
print "                            </form>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "            <div class=\"copyright\">\n";
print "                <div class=\"container\">\n";
print "                    <p>© 2024 - <a href=\"#\">Domnique&co</a></p>\n";
print "                </div>\n";
print "            </div>\n";
print "        </footer>\n";
print "\n";
print "\n";
print "        <div class=\"overlay \" data-overlay></div>\n";
print "\n";
print "            <nav class=\"mobile \" data-show>\n";
print "                 <a href=\"#\" class=\"close-trigger\" data-close-btn><i class=\"ri-close-line\"></i></a>\n";
print "                <ul>\n";
print "                    <li><a href=\"#\">Acceuil</a></li>\n";
print "                    <li><a href=\"#\">Produits</a>\n";
print "                        <span class=\"sub-trigger\"><i class=\"ri-arrow-down-s-line\"></i></span>\n";
print "                        <ul class=\"submenu\">\n";
print "                            <li><a href=\"#\">Louis Vuitton</a></li>\n";
print "                            <li><a href=\"#\">Lacoste</a></li>\n";
print "                            <li><a href=\"#\">Prada</a></li>\n";
print "                            <li><a href=\"#\">Balenciaga</a></li>\n";
print "                        </ul>\n";
print "                    </li>\n";
print "                    <li><a href=\"#\">Blog</a></li>\n";
print "                    <li><a href=\"#\">Hot offer</a></li>\n";
print "                </ul>\n";
print "                <div class=\"enter\">\n";
print "                    <div><span>Enter</span></div>\n";
print "                    <a href=\"#\" class=\"btn-primary\">Login</a>\n";
print "                    <a href=\"#\" class=\"btn-light\">Signup</a>\n";
print "                </div>\n";
print "            </nav>\n";
print "\n";
print "            <div class=\"search-modal active\"  data-show>\n";
print "                <div class=\"container\">\n";
print "                    <div class=\"wrap\">\n";
print "                        <div class=\"search-head\">\n";
print "                            <strong>Recherche</strong>\n";
print "                            <a href=\"#0\" class=\"close-trigger\" data-close-btn><i class=\"ri-close-line\"></i></a>\n";
print "                        </div>\n";
print "                        <form action=\"\" class=\"search\">\n";
print "                            <i class=\"ri-search-line\"></i>\n";
print "                            <input type=\"search\" placeholder=\"Search products\">\n";
print "                            <input type=\"submit\">\n";
print "                            <i class=\"ri-arrow-right-line\"></i>\n";
print "                        </form>\n";
print "                        <div class=\"search-footer\">\n";
print "                            <p>\n";
print "                                <span>Recherches populaires:</span>\n";
print "                                <a href=\"#0\">Louis Vuitton</a>\n";
print "                                <a href=\"#0\">Lacoste</a>\n";
print "                                <a href=\"#0\">Balenciaga</a>\n";
print "                            </p>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "\n";
print "            <div class=\"youtube\" data-show>\n";
print "                <div class=\"wrap\">\n";
print "                    <div class=\"inner\">\n";
print "                        <div class=\"item\">\n";
print "                            <a href=\"#0\" class=\"close-trigger\" data-close-btn><i class=\"ri-close-line\"></i></a>\n";
print "                            <div class=\"outer\">\n";
print "                                <div class=\"control\">\n";
print "                                    <iframe \n";
print "                                        src=\"https://www.youtube.com/embed/hXPgfdxFIlg?autoplay=1\" \n";
print "                                        frameborder=\"0\"\n";
print "                                        allowfullscreen>\n";
print "                                    </iframe>\n";
print "                                </div>\n";
print "                            </div>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "    </div>\n";
print "    <script src=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js\"></script>\n";
print "    <script src=\"script.js\"></script>\n";
print "</body>\n";
print "</html>";

?>
